services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "secret" ]

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"