services:
  zipkin-service:
    image: openzipkin/zipkin
    restart: on-failure
    ports:
      - "9411:9411"

  configuration-service:
    image: docker.io/library/configuration-service:0.0.1-SNAPSHOT
    restart: on-failure
    depends_on:
      - kafka
      - zipkin-service

  discovery-service:
    image: docker.io/library/discovery-service:0.0.1-SNAPSHOT
    restart: on-failure
    depends_on:
      - configuration-service
    ports:
      - "8761:8761"

  postgres:
    image: postgres:latest
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: social_network_db
    ports:
      - "5432:5432"

  subscriber-service:
    image: docker.io/library/subscriber-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: social_network_db
    depends_on:
      - discovery-service

  profile-service:
    image: docker.io/library/profile-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: social_network_db
    depends_on:
      - discovery-service

  posts-service:
    image: docker.io/library/posts-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: social_network_db
    depends_on:
      - discovery-service

  subscriber-post-service:
    image: docker.io/library/subscriber-post-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: social_network_db
    depends_on:
      - discovery-service

  web-service:
    image: docker.io/library/web-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: social_network_db
      API_AUTH_KEY: secret
      REDIS_PASSWORD: secret
    depends_on:
      - discovery-service
    ports:
      - "80:8080"

  redis:
    restart: on-failure
    image: redis:alpine

  gateway-service:
    image: docker.io/library/gateway-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      API_AUTH_KEY: secret
    depends_on:
      - discovery-service

volumes:
  postgres_data: