services:
  zipkin-service:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  configuration-service:
    image: docker.io/library/configuration-service:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    depends_on:
      - kafka
      - zipkin-service

  discovery-service:
    image: docker.io/library/discovery-service:0.0.1-SNAPSHOT
    depends_on:
      - configuration-service
    ports:
      - "8761:8761"

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"

  friends-service:
    image: docker.io/library/friends-service:0.0.1-SNAPSHOT
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - HIBERNATE_DDL_AUTO
    depends_on:
      - discovery-service

  profile-service:
    image: docker.io/library/profile-service:0.0.1-SNAPSHOT
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - HIBERNATE_DDL_AUTO
    depends_on:
      - discovery-service

  posts-service:
    image: docker.io/library/posts-service:0.0.1-SNAPSHOT
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - HIBERNATE_DDL_AUTO
    depends_on:
      - discovery-service

  share-posts-service:
    image: docker.io/library/share-posts-service:0.0.1-SNAPSHOT
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - HIBERNATE_DDL_AUTO
    depends_on:
      - discovery-service

  friend-posts-service:
    image: docker.io/library/friend-posts-service:0.0.1-SNAPSHOT
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - HIBERNATE_DDL_AUTO
    depends_on:
      - discovery-service

  web-service:
    image: docker.io/library/web-service:0.0.1-SNAPSHOT
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - HIBERNATE_DDL_AUTO
    depends_on:
      - discovery-service

  gateway-service:
    image: docker.io/library/gateway-service:0.0.1-SNAPSHOT
    depends_on:
      - discovery-service
    ports:
      - "8000:8000"

volumes:
  postgres_data: