create table if not exists profiles
(
    id        bigint generated by default as identity primary key,
    email     varchar(255),
    password  varchar(255) not null,
    photo_url varchar(255),
    username  varchar(255) not null
        unique
);

create table if not exists roles
(
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table if not exists profiles_roles
(
    profile_id bigint not null references profiles (id),
    role_id    bigint not null references roles (id),
    primary key (profile_id, role_id)
);

create table if not exists posts
(
    author_id  bigint references profiles (id) not null,
    created_at timestamp(6),
    id         bigint generated by default as identity primary key,
    content    varchar(255)                    not null,
    label      varchar(255)                    not null
);


create table if not exists profile_subscriber
(
    profile_id    bigint not null references profiles (id),
    subscriber_id bigint not null references profiles (id),
    primary key (profile_id, subscriber_id)
);



